bindm=SUPER,mouse:272,movewindow
bindm=SUPER,mouse:273,resizewindow

bind=SUPER, F, fullscreen, 1
bind=SUPERSHIFT, F, fullscreen, 0
bind=SUPER, V, togglefloating
bind=SUPER, T, pseudo
bind=SUPER, J, togglesplit

bind=SUPER, H, movefocus, l
bind=SUPER, L, movefocus, r
bind=SUPER, K, movefocus, u
bind=SUPER, J, movefocus, d
bind=SUPER, left, movefocus, l
bind=SUPER, right, movefocus, r
bind=SUPER, up, movefocus, u
bind=SUPER, down, movefocus, d

bind=SUPERSHIFT, H, movewindow, l
bind=SUPERSHIFT, L, movewindow, r
bind=SUPERSHIFT, K, movewindow, u
bind=SUPERSHIFT, J, movewindow, d
bind=SUPERSHIFT, left, movewindow, l
bind=SUPERSHIFT, right, movewindow, r
bind=SUPERSHIFT, up, movewindow, u
bind=SUPERSHIFT, down, movewindow, d

binde=SUPERALT, H, resizeactive, -25 0
binde=SUPERALT, L, resizeactive, 25 0
binde=SUPERALT, K, resizeactive, 0 -25
binde=SUPERALT, J, resizeactive, 0 25
binde=SUPERALT, left, resizeactive, -25 0
binde=SUPERALT, right, resizeactive, 25 0
binde=SUPERALT, up, resizeactive, 0 -25
binde=SUPERALT, down, resizeactive, 0 25

binde=SUPER, X, killactive

bind=SUPER, 1, workspace, 1
bind=SUPER, 2, workspace, 2
bind=SUPER, 3, workspace, 3
bind=SUPER, 4, workspace, 4
bind=SUPER, 5, workspace, 5

bind=SUPERSHIFT, 1, movetoworkspacesilent, 1
bind=SUPERSHIFT, 2, movetoworkspacesilent, 2
bind=SUPERSHIFT, 3, movetoworkspacesilent, 3
bind=SUPERSHIFT, 4, movetoworkspacesilent, 4
bind=SUPERSHIFT, 5, movetoworkspacesilent, 5

bind=SUPER, mouse_down, workspace, e-1
bind=SUPER, mouse_up, workspace, e+1

bindr=SUPER, F1, exec, ~/.local/bin/cheatsheet.sh
bind=SUPER,S,exec, ~/.local/bin/screenshot.sh
bind=,Print,exec, grim ~/Pictures/Screenshots/$(date +%d-%m-%Y_%H-%m-%s).png
bind=,Print,exec, notify-send "Screenshot taken" "Saved as $(date '+%d-%m-%Y_%H-%m-%s').png"
bind=SUPER ALT, Space, exec, ~/.local/bin/wallpaper.sh
bind=SUPERCONTROL,Q,exec, qs ipc call lockscreen lock
bind=SUPER,ESCAPE,exec, ~/.local/bin/powermenu.sh
bind=SUPER,C,exec, ~/.local/bin/clipboard.sh
bind=SUPER,P,exec, ~/.local/bin/powerprofiles.sh

bindr=SUPER, Space, exec, rofi -show drun
bind=SUPER, Return, exec, kitty
bind=SUPER, E, exec, thunar
bind=SUPER, B, exec, zen-browser
bind=SUPER, G, exec, lutris

bind=, XF86AudioMute, exec, wpctl set-mute @DEFAULT_SINK@ toggle
bind=, XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_SOURCE@ toggle
binde=, XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_SINK@ 0.05-
binde=, XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_SINK@ 0.05+
binde=, XF86MonBrightnessdown, exec, brightnessctl -e4 -n2 set 5%-
binde=, XF86MonBrightnessup, exec, brightnessctl -e4 -n2 set 5%+
bind=, XF86AudioPlay, exec, playerctl play-pause
bind=, XF86AudioNext, exec, playerctl next
bind=, XF86AudioPrev, exec, playerctl previous
